root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/coreservice ./cmd/coreservice"
  bin = "./tmp/coreservice"
  include_ext = ["go"]
  exclude_dir = ["tmp", "bin", "migrations", "deployments", ".git", ".idea"]
  delay = 200

[log]
  time = true