// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/proto/link.proto

package linkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_api_proto_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_link_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_api_proto_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_link_proto_rawDescGZIP(), []int{1}
}

func (x *GetLinkRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_api_proto_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_api_proto_link_proto_rawDescGZIP(), []int{2}
}

func (x *Link) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Link) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *Link) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_proto_link_proto protoreflect.FileDescriptor

const file_api_proto_link_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/link.proto\x12\alink.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"%\n" +
	"\x11CreateLinkRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"$\n" +
	"\x0eGetLinkRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"p\n" +
	"\x04Link\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2y\n" +
	"\vLinkService\x127\n" +
	"\n" +
	"CreateLink\x12\x1a.link.v1.CreateLinkRequest\x1a\r.link.v1.Link\x121\n" +
	"\aGetLink\x12\x17.link.v1.GetLinkRequest\x1a\r.link.v1.LinkB&Z$URLShortener/api/proto/linkpb;linkpbb\x06proto3"

var (
	file_api_proto_link_proto_rawDescOnce sync.Once
	file_api_proto_link_proto_rawDescData []byte
)

func file_api_proto_link_proto_rawDescGZIP() []byte {
	file_api_proto_link_proto_rawDescOnce.Do(func() {
		file_api_proto_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_link_proto_rawDesc), len(file_api_proto_link_proto_rawDesc)))
	})
	return file_api_proto_link_proto_rawDescData
}

var file_api_proto_link_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_link_proto_goTypes = []any{
	(*CreateLinkRequest)(nil),     // 0: link.v1.CreateLinkRequest
	(*GetLinkRequest)(nil),        // 1: link.v1.GetLinkRequest
	(*Link)(nil),                  // 2: link.v1.Link
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_proto_link_proto_depIdxs = []int32{
	3, // 0: link.v1.Link.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: link.v1.LinkService.CreateLink:input_type -> link.v1.CreateLinkRequest
	1, // 2: link.v1.LinkService.GetLink:input_type -> link.v1.GetLinkRequest
	2, // 3: link.v1.LinkService.CreateLink:output_type -> link.v1.Link
	2, // 4: link.v1.LinkService.GetLink:output_type -> link.v1.Link
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_link_proto_init() }
func file_api_proto_link_proto_init() {
	if File_api_proto_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_link_proto_rawDesc), len(file_api_proto_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_link_proto_goTypes,
		DependencyIndexes: file_api_proto_link_proto_depIdxs,
		MessageInfos:      file_api_proto_link_proto_msgTypes,
	}.Build()
	File_api_proto_link_proto = out.File
	file_api_proto_link_proto_goTypes = nil
	file_api_proto_link_proto_depIdxs = nil
}
