// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/proto/stats.proto

package statspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	TotalClicks   int64                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	LastClickedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_clicked_at,json=lastClickedAt,proto3" json:"last_clicked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StatsResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *StatsResponse) GetLastClickedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastClickedAt
	}
	return nil
}

var File_api_proto_stats_proto protoreflect.FileDescriptor

const file_api_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/stats.proto\x12\bstats.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"%\n" +
	"\x0fGetStatsRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x8a\x01\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x03R\vtotalClicks\x12B\n" +
	"\x0flast_clicked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rlastClickedAt2N\n" +
	"\fStatsService\x12>\n" +
	"\bGetStats\x12\x19.stats.v1.GetStatsRequest\x1a\x17.stats.v1.StatsResponseB(Z&URLShortener/api/proto/statspb;statspbb\x06proto3"

var (
	file_api_proto_stats_proto_rawDescOnce sync.Once
	file_api_proto_stats_proto_rawDescData []byte
)

func file_api_proto_stats_proto_rawDescGZIP() []byte {
	file_api_proto_stats_proto_rawDescOnce.Do(func() {
		file_api_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_stats_proto_rawDesc), len(file_api_proto_stats_proto_rawDesc)))
	})
	return file_api_proto_stats_proto_rawDescData
}

var file_api_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_stats_proto_goTypes = []any{
	(*GetStatsRequest)(nil),       // 0: stats.v1.GetStatsRequest
	(*StatsResponse)(nil),         // 1: stats.v1.StatsResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_proto_stats_proto_depIdxs = []int32{
	2, // 0: stats.v1.StatsResponse.last_clicked_at:type_name -> google.protobuf.Timestamp
	0, // 1: stats.v1.StatsService.GetStats:input_type -> stats.v1.GetStatsRequest
	1, // 2: stats.v1.StatsService.GetStats:output_type -> stats.v1.StatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_stats_proto_init() }
func file_api_proto_stats_proto_init() {
	if File_api_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_stats_proto_rawDesc), len(file_api_proto_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_stats_proto_goTypes,
		DependencyIndexes: file_api_proto_stats_proto_depIdxs,
		MessageInfos:      file_api_proto_stats_proto_msgTypes,
	}.Build()
	File_api_proto_stats_proto = out.File
	file_api_proto_stats_proto_goTypes = nil
	file_api_proto_stats_proto_depIdxs = nil
}
